/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilTest {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLStencilTestElement extends Components.StencilTest, HTMLStencilElement {
    }
    var HTMLStencilTestElement: {
        prototype: HTMLStencilTestElement;
        new (): HTMLStencilTestElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-test": HTMLStencilTestElement;
    }
}
declare namespace LocalJSX {
    interface StencilTest {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "stencil-test": StencilTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-test": LocalJSX.StencilTest & JSXBase.HTMLAttributes<HTMLStencilTestElement>;
        }
    }
}
